// <auto-generated />
using System;
using GestionCoutureApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCoutureApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730204755_AjoutDepenses")]
    partial class AjoutDepenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GestionCoutureApp.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminPhoto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionPrecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HeureFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdClient")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCommission")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCouturier")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeVetement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCommande");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCommission");

                    b.HasIndex("IdCouturier");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commission", b =>
                {
                    b.Property<int>("IdCommission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCalcul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseMontant")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCalcul")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebutPeriode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFinPeriode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstAnnulee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEmploye")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdOperateur")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantCommission")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotifAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<int>("NbCommandes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomAnnulateur")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEmployeSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomOperateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pourcentage")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCommission");

                    b.HasIndex("IdEmploye");

                    b.ToTable("Commissions");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Depense", b =>
                {
                    b.Property<int>("IdDepense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDepense")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomOperateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeDepense")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdDepense");

                    b.ToTable("Depenses");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.DescriptionCourante", b =>
                {
                    b.Property<int>("IdDescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdDescription");

                    b.Property<int>("IdTypeVetement")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdTypeVetement");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("IdDescription");

                    b.HasIndex("IdTypeVetement");

                    b.ToTable("DescriptionsCourantes");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Employe", b =>
                {
                    b.Property<int>("IdEmploye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Actif");

                    b.HasKey("IdEmploye");

                    b.HasIndex("Identifiant")
                        .IsUnique();

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Mesure", b =>
                {
                    b.Property<int>("IdMesure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCommande")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdPieceCommande")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomMesure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMesure");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdPieceCommande");

                    b.ToTable("Mesures");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.MesureRequise", b =>
                {
                    b.Property<int>("IdMesureRequise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTypeVetement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomMesure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMesureRequise");

                    b.HasIndex("IdTypeVetement");

                    b.ToTable("MesuresRequises");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstAnnule")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCommande")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdOperateur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTotalCommande")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotifsAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomAnnulateur")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomOperateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecuNumero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ResteAvantPaiement")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPaiement");

                    b.HasIndex("IdCommande");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Parametre", b =>
                {
                    b.Property<string>("Cle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Cle");

                    b.ToTable("Parametres");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.PieceCommande", b =>
                {
                    b.Property<int>("IdPieceCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminPhoto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionPrecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCommande")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCommission")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCouturier")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantCouture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RendezVousException")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeVetement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPieceCommande");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdCommission");

                    b.HasIndex("IdCouturier");

                    b.ToTable("PiecesCommande");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Retour", b =>
                {
                    b.Property<int>("IdRetour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSignalement")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionProbleme")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCommande")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCouturier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdOperateurEnregistrement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdOperateurResolution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPieceCommande")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomOperateurEnregistrement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomOperateurResolution")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRetour");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdCouturier");

                    b.HasIndex("IdPieceCommande");

                    b.ToTable("Retours");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.TypeVetement", b =>
                {
                    b.Property<int>("IdTypeVetement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixBase")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTypeVetement");

                    b.ToTable("TypesVetements");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commande", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionCoutureApp.Models.Commission", "Commission")
                        .WithMany("Commandes")
                        .HasForeignKey("IdCommission")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionCoutureApp.Models.Employe", "Couturier")
                        .WithMany()
                        .HasForeignKey("IdCouturier");

                    b.Navigation("Client");

                    b.Navigation("Commission");

                    b.Navigation("Couturier");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commission", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("IdEmploye")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.DescriptionCourante", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.TypeVetement", "TypeVetement")
                        .WithMany("Descriptions")
                        .HasForeignKey("IdTypeVetement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeVetement");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Mesure", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Commande", "Commande")
                        .WithMany("Mesures")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCoutureApp.Models.PieceCommande", "PieceCommande")
                        .WithMany("Mesures")
                        .HasForeignKey("IdPieceCommande")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Commande");

                    b.Navigation("PieceCommande");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.MesureRequise", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.TypeVetement", "TypeVetement")
                        .WithMany("MesuresRequises")
                        .HasForeignKey("IdTypeVetement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeVetement");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Paiement", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Commande", "Commande")
                        .WithMany("Paiements")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.PieceCommande", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Commande", "Commande")
                        .WithMany("Pieces")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCoutureApp.Models.Commission", "Commission")
                        .WithMany("Pieces")
                        .HasForeignKey("IdCommission")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionCoutureApp.Models.Employe", "Couturier")
                        .WithMany()
                        .HasForeignKey("IdCouturier");

                    b.Navigation("Commande");

                    b.Navigation("Commission");

                    b.Navigation("Couturier");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Retour", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCoutureApp.Models.Employe", "Couturier")
                        .WithMany()
                        .HasForeignKey("IdCouturier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCoutureApp.Models.PieceCommande", "PieceCommande")
                        .WithMany()
                        .HasForeignKey("IdPieceCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Couturier");

                    b.Navigation("PieceCommande");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commande", b =>
                {
                    b.Navigation("Mesures");

                    b.Navigation("Paiements");

                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commission", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.PieceCommande", b =>
                {
                    b.Navigation("Mesures");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.TypeVetement", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("MesuresRequises");
                });
#pragma warning restore 612, 618
        }
    }
}
