// <auto-generated />
using System;
using GestionCoutureApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GestionCoutureApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918000000_AjoutContrainteUniqueRecuNumero")]
    partial class AjoutContrainteUniqueRecuNumero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Note: Ce fichier .Designer.cs est généré automatiquement par EF Core
            // Il contient une snapshot du modèle au moment de la migration
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
#pragma warning restore 612, 618
        }
    }
}
