// <auto-generated />
using System;
using GestionCoutureApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCoutureApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260719120000_AjoutForceChangementMotDePasse")]
    partial class AjoutForceChangementMotDePasse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GestionCoutureApp.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminPhoto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionPrecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HeureFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdClient")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCommission")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCouturier")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MontantTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeVetement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCommande");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCommission");

                    b.HasIndex("IdCouturier");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commission", b =>
                {
                    b.Property<int>("IdCommission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCalcul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("BaseMontant")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCalcul")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebutPeriode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFinPeriode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstAnnulee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEmploye")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdOperateur")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MontantCommission")
                        .HasColumnType("REAL");

                    b.Property<string>("MotifAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<int>("NbCommandes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomAnnulateur")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEmployeSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomOperateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Pourcentage")
                        .HasColumnType("REAL");

                    b.HasKey("IdCommission");

                    b.HasIndex("IdEmploye");

                    b.ToTable("Commissions");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.DescriptionCourante", b =>
                {
                    b.Property<int>("IdDescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdDescription");

                    b.Property<int>("IdTypeVetement")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdTypeVetement");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("IdDescription");

                    b.HasIndex("IdTypeVetement");

                    b.ToTable("DescriptionsCourantes");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Employe", b =>
                {
                    b.Property<int>("IdEmploye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoitChangerMotDePasse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Actif");

                    b.HasKey("IdEmploye");

                    b.HasIndex("Identifiant")
                        .IsUnique();

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Mesure", b =>
                {
                    b.Property<int>("IdMesure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCommande")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomMesure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMesure");

                    b.HasIndex("IdCommande");

                    b.ToTable("Mesures");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.MesureRequise", b =>
                {
                    b.Property<int>("IdMesureRequise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTypeVetement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomMesure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMesureRequise");

                    b.HasIndex("IdTypeVetement");

                    b.ToTable("MesuresRequises");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstAnnule")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCommande")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdOperateur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MontantPaye")
                        .HasColumnType("REAL");

                    b.Property<double>("MontantTotalCommande")
                        .HasColumnType("REAL");

                    b.Property<string>("MotifsAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomAnnulateur")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomOperateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecuNumero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ResteAvantPaiement")
                        .HasColumnType("REAL");

                    b.HasKey("IdPaiement");

                    b.HasIndex("IdCommande");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.TypeVetement", b =>
                {
                    b.Property<int>("IdTypeVetement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PrixBase")
                        .HasColumnType("REAL");

                    b.HasKey("IdTypeVetement");

                    b.ToTable("TypesVetements");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commande", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionCoutureApp.Models.Commission", "Commission")
                        .WithMany("Commandes")
                        .HasForeignKey("IdCommission")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionCoutureApp.Models.Employe", "Couturier")
                        .WithMany()
                        .HasForeignKey("IdCouturier");

                    b.Navigation("Client");

                    b.Navigation("Commission");

                    b.Navigation("Couturier");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commission", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("IdEmploye")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.DescriptionCourante", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.TypeVetement", "TypeVetement")
                        .WithMany("Descriptions")
                        .HasForeignKey("IdTypeVetement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeVetement");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Mesure", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Commande", "Commande")
                        .WithMany("Mesures")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.MesureRequise", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.TypeVetement", "TypeVetement")
                        .WithMany("MesuresRequises")
                        .HasForeignKey("IdTypeVetement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeVetement");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Paiement", b =>
                {
                    b.HasOne("GestionCoutureApp.Models.Commande", "Commande")
                        .WithMany("Paiements")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commande", b =>
                {
                    b.Navigation("Mesures");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.Commission", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("GestionCoutureApp.Models.TypeVetement", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("MesuresRequises");
                });

#pragma warning restore 612, 618
        }
    }
}
